// const fs= require('fs')
// const first=fs.readFileSync('./content/first.txt','utf8')
// const second= fs.readFileSync('./content/second.txt','utf8')
const {readFileSync, writeFileSync}= require('fs')
const first=readFileSync('./content/first.txt','utf8')
const second=readFileSync('./content/second.txt','utf8')
console.log(first)
console.log(second)

 writeFileSync('./content/result.txt', `the result written is: ${first} ${second}`, {flag:'a'})